version: "3.8"

services:
  golang-api:
    image: ghcr.io/gilbertdaniel/golang-api-ci-cd/my-golang-api:latest
    ports:
      - "8080:8080"
    networks:
      - golang-api-net
    restart: unless-stopped

networks:
  golang-api-net:
    driver: bridge
