name: Docker Build and Push to GHCR

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3 # Already up to date and supports Node.js 20

      # Step 2: Log in to GitHub Container Registry using the Personal Access Token
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Set up Docker Buildx (make sure to use v3 for Node.js 20 support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: docker build -t ghcr.io/gilbertdaniel/my-golang-api:latest .

      # Step 5: Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/gilbertdaniel/my-golang-api:latest
